services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: amigoscode
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411
    networks:
      - zipkin

  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - rabbitmq

  eureka-server:
    image: nadirakdag/eureka-server:latest
    container_name: eureka-server
    ports:
      - 8761:8761
    depends_on:
      - zipkin
    networks:
      - spring

  api-gateway:
    image: nadirakdag/apigw:latest
    container_name: api-gateway
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - 8083:8083
    depends_on:
      - eureka-server
      - zipkin
    networks:
      - spring
      - zipkin

  customer:
    image: nadirakdag/customer:latest
    container_name: customer-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - eureka-server
      - api-gateway
      - postgres
      - rabbitmq
    networks:
      - spring
      - postgres
      - rabbitmq
      - zipkin

  fraud:
    image: nadirakdag/fraud:latest
    container_name: fraud-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - eureka-server
      - api-gateway
      - postgres
    networks:
      - spring
      - postgres
      - zipkin

  notification:
    image: nadirakdag/notification:latest
    container_name: notification-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - eureka-server
      - api-gateway
      - postgres
      - rabbitmq
    networks:
      - spring
      - postgres
      - rabbitmq
      - zipkin

networks:
  rabbitmq:
    driver: bridge
  postgres:
    driver: bridge
  spring:
    driver: bridge
  zipkin:
    driver: bridge

volumes:
  postgres:
  pgadmin:
