apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-deployment
  labels:
    app: notification-service
spec:
  replicas: 1
  template:
    metadata:
      name: notification-template
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-container
          image: nadirakdag/notification
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
      restartPolicy: Always
  selector:
    matchLabels:
      app: notification-service